controller_manager:
  ros__parameters:
    update_rate: 50
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_left_wheel"]
    right_wheel_names: ["joint_right_wheel"]
    wheel_separation: 0.16
    wheel_radius: 0.033
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    base_frame_id: base_footprint 
    odom_frame_id: odom
    
    publish_rate: 50.0 
    enable_odom_tf: false
    cmd_vel_timeout: 2.0
    is_stamped_cmd_vel: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0
        min_velocity: -2.0
        has_acceleration_limits: true
        max_acceleration: 2.0
        min_acceleration: -2.0