slam_toolbox:
  ros__parameters:

    mode: localization
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None
    # Frame
    map_frame: map
    odom_frame: odom
    base_frame: base_footprint

    scan_topic: /scan
    map_file_name: /home/edoardo/ros2_ws/src/navigation/maps/casa_serialized
    map_update_interval: 0.0
    do_loop_closing: false
    enable_interactive_mode: false

    transform_publish_period: 0.05
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # Scan matcher
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    debug_logging: false
